### ISSUE TITLE
Building Windows Binaries

### ISSUE THREAD

**Issue by nathanshearer** [libguestfs/nbdkit#14]
I am trying to build some windows binaries of nbdkit as I have some files on a windows host that I need to exporte as nbd block devices to another system.

I first attempted to configure and build nbdkit under cygwin with these packages installed on a windows 10 computer:
- automake 11-1
- gcc-core 10.2.0-1
- gcc-g++ 10.2.0-1
- libtool 2.4.6-7
- make 4.3-1
- pkg-config 1.6.3-1

The autoconf and configure steps work fine, however it fails during the make step due to some compile-time bugs in the code relating to conflicting definitions in some included headers.

Can you please include some more detail on how to cross-compile windows binaries of nbdkit, on a linux host. I assume your document is referring to debian/ubuntu? If you used a different distro please include that too as it will help me reproduce the process.

**Comment by rwmjones** [comment]
-> https://listman.redhat.com/archives/libguestfs/2021-July/msg00028.html
