### ISSUE TITLE
A potential error due to the unreleased lock 

### ISSUE THREAD

**Issue by ycaibb** [libguestfs/nbdkit#15]
Dear developers: Thank you for your checking. It seems there is a lock resource leak on the lock `paused`. I think the lock should be released at the end of  `do_pause`?

https://github.com/libguestfs/nbdkit/blob/9c19c0b3a8f8c3d248d353e97f87d4e49be9e832/filters/pause/pause.c#L146-L163

**Comment by rwmjones** [comment]
Which lock do you mean?

**Comment by ycaibb** [comment]
This one
https://github.com/libguestfs/nbdkit/blob/9c19c0b3a8f8c3d248d353e97f87d4e49be9e832/filters/pause/pause.c#L152

**Comment by rwmjones** [comment]
It is unlocked in the next function.

**Comment by ycaibb** [comment]
But here is a `break`?
https://github.com/libguestfs/nbdkit/blob/9c19c0b3a8f8c3d248d353e97f87d4e49be9e832/filters/pause/pause.c#L198-L202
https://github.com/libguestfs/nbdkit/blob/9c19c0b3a8f8c3d248d353e97f87d4e49be9e832/filters/pause/pause.c#L166-L174

**Comment by rwmjones** [comment]
https://libguestfs.org/nbdkit-pause-filter.1.html#Control-socket
Would suggest reading how the pause filter works.  Unless there is a specific problem you are seeing I will close this issue.  BTW gitlab is the site used for nbdkit:  https://gitlab.com/nbdkit/nbdkit

**Comment by ycaibb** [comment]
This case is detected by our static code analyzer, which might be a false positive. Thank you very much for your time.
