### ISSUE TITLE
nbdkit not not support tls13-ciphers?

### ISSUE THREAD

**Issue by gezhen1** [libguestfs/nbdkit#20]
I use nbdkit to connect to the https server, and the following error occurs：
“nbdkit: curl[1]: error: tls13-ciphers is not supported in this build of nbdkit-curl-plugin”

**Comment by rwmjones** [comment]
Note this is not the upstream for nbdkit, it's: https://gitlab.com/nbdkit/nbdkit

You probably need this commit: https://gitlab.com/nbdkit/nbdkit/-/commit/242757dd5c9fbf00a487ab934d67db442fe08661
