### ISSUE TITLE
Plugin Callback Issues in Rust Library

### ISSUE THREAD

**Issue by dcullen12** [libguestfs/nbdkit#21]
For reference using `nbdkit = "0.2.0"` (appears to be latest version on crates.io)

Noticed a couple gaps in the rust library for writing plugins:

1. open() does not return `Result<Box<dyn Server>>`, instead it simply returns `Box<dyn Server>`
    - because of this I have to create a struct full of OnceCells and actually initialize things in get_size(). I would rather do the initialization in open() and potentially return an error. This would remove the need for OnceCell (not a huge performance difference, and get_size will fail the connection all the same. But the code would be cleaner this way)

2. there is no after_fork() callback. I ran into some bugs where a lazy_static tokio runtime was being accessed (and therefor initialized) too early (before fork). this resulted in failures when the runtime was used after fork() (presumably due to the loss of the runtime's internal threads). it would be nice to have after_fork() to verify at startup time that the runtime is in a good state (and panic accordingly if not). in general, it appears inconvenient to spin up background threads for Rust plugins. right now these checks can only be done retrospectively when a connection is opened, which is undesirable (server should fail to start up rather than mislead user into thinking it is good-to-go until an actual connections happens.)

**Comment by rwmjones** [comment]
Note the actual repo is https://gitlab.com/nbdkit/nbdkit  This is a mirror.  And out of date because I notice the mirroring stopped working ...

@asomers ^

**Comment by rwmjones** [comment]
`after_fork` is definitely needed by any plugin that uses threads.  We originally introduced it after noticing strange problems in a 3rd party library, which turned out to be because the library was creating threads at start-up which were then killed by forking.

**Comment by asomers** [comment]
Yes, I think both of those features could be added.  Would you care to submit a PR?

**Comment by rwmjones** [comment]
A posted a simple implementation of `after_fork` here: https://listman.redhat.com/archives/libguestfs/2023-April/031353.html

**Comment by rwmjones** [comment]
`after_fork` support is present in commit d62f26808ea1fa2cf97d990745b76010caffe7d4

**Comment by rwmjones** [comment]
For the other change see https://gitlab.com/nbdkit/nbdkit/-/merge_requests/23
