### ISSUE TITLE
Publish Rust bindings to crates.io

### ISSUE THREAD

**Issue by asomers** [libguestfs/nbdkit#4]
Would you consider publishing the Rust plugin to crates.io?  That would make it easier to use.  Right now, users must manually check out the nbdkit source code, and specify it by path in their `Cargo.toml` files.

**Comment by rwmjones** [comment]
Can you do it for us?  I guess you already have the crates.io account etc.

**Comment by asomers** [comment]
Technically I can.  But that would make me responsible for maintaining the crate, which I can't do, since I don't have push access to the repository.  If I must be the maintainer of the crate, I'll create a separate repository for it.

**Comment by asomers** [comment]
https://crates.io/crates/nbdkit/
