### ISSUE TITLE
Rust bindings should include nbdkit_error

### ISSUE THREAD

**Issue by asomers** [libguestfs/nbdkit#5]
Currently there's no way for the Rust plugin to report an error.  The idiomatic way to do it would be for each callback to return a `Result` object, much like how the Go plugin currently does it.

**Comment by rwmjones** [comment]
I think the best way to make this happen is to provide patches.  BTW please post patches on the mailing list (you don't have to subscribe), by emailing them to mailto:libguestfs@redhat.com

**Comment by asomers** [comment]
I plan to.  However, my effort is sort of turning into rewriting the whole crate, in an attempt to make the API more idiomatic.  Do you only accept patches via mailing list and not via PRs?

**Comment by rwmjones** [comment]
The basic bindings that I added were only interim until someone came along who cared more and wanted to write more idiomatic bindings.  So if you want to do that, all the better.  I doubt very much anyone is writing Rust plugins for nbdkit using the current system, or at least no one has mentioned it to us.

We'd prefer it on the mailing list.  If you send it as a PR then I'll have to forward it to the mailing list for review.  Note that you don't have to subscribe, just git send-email them to the address.
