### ISSUE TITLE
Request for pre-built Windows 10 binaries

### ISSUE THREAD

**Issue by tomjridge** [libguestfs/nbdkit#7]
Dear Richard,

A bit embarrassing... I can't face trying to cross-compile to Windows. Would it be possible to provide a pre-built nbdkit.exe server?

Thanks

**Comment by rwmjones** [comment]
I can't really promise that I'll update this often, but I placed the current binaries that I've built / am testing here: http://oirase.annexia.org/nbdkit/  Please read the README file there first.  If this becomes popular we may need to think about a long term way to build / test / distribute them.

**Comment by tomjridge** [comment]
Wow! Thank you so much. Very much appreciated.

Tom

**Comment by tomjridge** [comment]
Just to follow up- I used cygwin to install mingw and the relevant (mingw) libraries. Then I copied lots of mingw dlls to a directory which contained a copy of your binaries downloaded from above. And it all seems to work. Great!

**Comment by rwmjones** [comment]
Yeah if we did this more routinely we'd need to find a way to distribute all the DLLs as well, which is complicated because many of them are not as permissively licensed as nbdkit so we'd have to include sources.  Glad that it worked anyhow.
